name: Run Node App

on:
  push:
    branches: [ main ]

jobs:
  run-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
            node-version: 20

      - run: npm install

      - name: Verify server starts
        run: timeout 5s node index.js
